In [1]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00232/RCdata.zip

--2021-10-08 23:59:48--  https://archive.ics.uci.edu/ml/machine-learning-databases/00232/RCdata.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39674 (39K) [application/x-httpd-php]
Saving to: ‘RCdata.zip’

RCdata.zip          100%[===================>]  38.74K  --.-KB/s    in 0.06s

2021-10-08 23:59:48 (609 KB/s) - ‘RCdata.zip’ saved [39674/39674]

In [2]:
!unzip /content/RCdata.zip

Archive:  /content/RCdata.zip
  inflating: chefmozaccepts.csv
  inflating: chefmozcuisine.csv
  inflating: chefmozhours4.csv
  inflating: chefmozparking.csv
  inflating: geoplaces2.csv
  inflating: rating_final.csv
  inflating: README
  inflating: usercuisine.csv
  inflating: userpayment.csv
  inflating: userprofile.csv

In [3]:
import pandas as pd
 
accepts = pd.read_csv('/content/chefmozaccepts.csv')
cuisine = pd.read_csv('/content/chefmozcuisine.csv')
hours = pd.read_csv('/content/chefmozhours4.csv')
parking = pd.read_csv('/content/chefmozparking.csv')
geo = pd.read_csv('/content/geoplaces2.csv', encoding = "ISO-8859-1")
usercuisine = pd.read_csv('/content/usercuisine.csv')
payment = pd.read_csv('/content/userpayment.csv')
profile = pd.read_csv('/content/userprofile.csv')
rating = pd.read_csv('/content/rating_final.csv')
 
print('Jumlah data pembayaran yang diterima restoran: ', len(accepts.placeID.unique()))
print('Jumlah data masakan pada restoran: ', len(cuisine.placeID.unique()))
print('Jumlah data waktu buka restoran: ', len(hours.placeID.unique()))
print('Jumlah data lokasi restoran: ', len(geo.placeID.unique()))
print('Jumlah data masakan pengguna: ', len(usercuisine.userID.unique()))
print('Jumlah data profil pengguna: ', len(profile.userID.unique()))
print('Jumlah data penilaian yang diberikan pengguna: ', len(rating.userID.unique()))
print('Jumlah data penilaian restoran: ', len(rating.placeID.unique()))

Jumlah data pembayaran yang diterima restoran:  615
Jumlah data masakan pada restoran:  769
Jumlah data waktu buka restoran:  694
Jumlah data lokasi restoran:  130
Jumlah data masakan pengguna:  138
Jumlah data profil pengguna:  138
Jumlah data penilaian yang diberikan pengguna:  138
Jumlah data penilaian restoran:  130

In [4]:
accepts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1314 entries, 0 to 1313
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   placeID   1314 non-null   int64
 1   Rpayment  1314 non-null   object
dtypes: int64(1), object(1)
memory usage: 20.7+ KB

In [5]:
print('Banyak data: ', len(accepts.placeID.unique()))
print('Jenis Pembayaran yang diterima: ', accepts.Rpayment.unique())

Banyak data:  615
Jenis Pembayaran yang diterima:  ['cash' 'VISA' 'MasterCard-Eurocard' 'American_Express' 'bank_debit_cards'
 'checks' 'Discover' 'Carte_Blanche' 'Diners_Club' 'Visa'
 'Japan_Credit_Bureau' 'gift_certificates']

In [6]:
cuisine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 916 entries, 0 to 915
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   placeID   916 non-null    int64
 1   Rcuisine  916 non-null    object
dtypes: int64(1), object(1)
memory usage: 14.4+ KB

In [7]:
print('Banyak tipe masakan: ', len(cuisine.Rcuisine.unique()))
print('Tipe masakan: ', cuisine.Rcuisine.unique())

Banyak tipe masakan:  59
Tipe masakan:  ['Spanish' 'Italian' 'Latin_American' 'Mexican' 'Fast_Food' 'Burgers'
 'Dessert-Ice_Cream' 'Hot_Dogs' 'Steaks' 'Asian' 'International'
 'Mongolian' 'Vegetarian' 'Brazilian' 'Cafe-Coffee_Shop' 'Cafeteria'
 'Contemporary' 'Deli-Sandwiches' 'Diner' 'Japanese' 'Sushi' 'Seafood'
 'Chinese' 'Bar' 'Bar_Pub_Brewery' 'Pizzeria' 'Mediterranean' 'American'
 'Family' 'Caribbean' 'African' 'Breakfast-Brunch' 'Regional' 'Afghan'
 'Bakery' 'Game' 'Armenian' 'Vietnamese' 'Korean' 'Thai' 'Barbecue'
 'Polish' 'Dutch-Belgian' 'French' 'German' 'Southwestern' 'Persian'
 'Ethiopian' 'Juice' 'Soup' 'Continental-European' 'Greek' 'Southern'
 'Eastern_European' 'California' 'Bagels' 'Turkish' 'Organic-Healthy'
 'Fine_Dining']

In [8]:
print(profile.shape)

(138, 19)

In [9]:
profile.head()

  userID   latitude   longitude smoker  ...  color weight  budget height
0  U1001  22.139997 -100.978803  false  ...  black     69  medium   1.77
1  U1002  22.150087 -100.983325  false  ...    red     40     low   1.87
2  U1003  22.119847 -100.946527  false  ...   blue     60     low   1.69
3  U1004  18.867000  -99.183000  false  ...  green     44  medium   1.53
4  U1005  22.183477 -100.959891  false  ...  black     65  medium   1.69

[5 rows x 19 columns]

In [10]:
rating.head()

  userID  placeID  rating  food_rating  service_rating
0  U1077   135085       2            2               2
1  U1077   135038       2            2               1
2  U1077   132825       2            2               2
3  U1077   135060       1            2               2
4  U1068   135104       1            1               2

In [11]:
rating.describe()

             placeID       rating  food_rating  service_rating
count    1161.000000  1161.000000  1161.000000     1161.000000
mean   134192.041344     1.199828     1.215332        1.090439
std      1100.916275     0.773282     0.792294        0.790844
min    132560.000000     0.000000     0.000000        0.000000
25%    132856.000000     1.000000     1.000000        0.000000
50%    135030.000000     1.000000     1.000000        1.000000
75%    135059.000000     2.000000     2.000000        2.000000
max    135109.000000     2.000000     2.000000        2.000000

In [12]:
print('Jumlah userID: ', len(rating.userID.unique()))
print('Jumlah placeID: ', len(rating.placeID.unique()))
print('Jumlah data rating: ', len(rating))

Jumlah userID:  138
Jumlah placeID:  130
Jumlah data rating:  1161

In [13]:
import numpy as np
 
# Menggabungkan seluruh placeID pada kategori Restaurant
resto_all = np.concatenate((
    accepts.placeID.unique(),
    cuisine.placeID.unique(),
    hours.placeID.unique(),
    parking.placeID.unique(),
    geo.placeID.unique()
))
 
# Mengurutkan data dan menghapus data yang sama
resto_all = np.sort(np.unique(resto_all))
 
print('Jumlah seluruh data restoran berdasarkan placeID: ', len(resto_all))

Jumlah seluruh data restoran berdasarkan placeID:  938

In [14]:
resto_all

array([132001, 132002, 132003, 132004, 132005, 132006, 132007, 132008,
       132009, 132010, 132012, 132013, 132014, 132015, 132016, 132017,
       132018, 132019, 132020, 132021, 132022, 132023, 132024, 132025,
       132026, 132028, 132030, 132031, 132083, 132087, 132092, 132094,
       132096, 132097, 132098, 132100, 132101, 132102, 132103, 132105,
       132106, 132107, 132108, 132109, 132111, 132114, 132115, 132116,
       132118, 132119, 132120, 132121, 132125, 132126, 132127, 132128,
       132130, 132131, 132132, 132133, 132136, 132137, 132138, 132145,
       132146, 132147, 132148, 132155, 132156, 132157, 132159, 132160,
       132161, 132162, 132163, 132164, 132165, 132166, 132167, 132171,
       132174, 132175, 132177, 132180, 132182, 132184, 132186, 132187,
       132191, 132192, 132201, 132203, 132204, 132206, 132207, 132208,
       132209, 132210, 132211, 132212, 132213, 132214, 132215, 132216,
       132217, 132218, 132220, 132221, 132223, 132225, 132226, 132228,
       132229, 132230, 132231, 132232, 132233, 132234, 132235, 132237,
       132238, 132239, 132240, 132242, 132243, 132244, 132245, 132246,
       132247, 132249, 132250, 132253, 132255, 132257, 132258, 132262,
       132265, 132266, 132268, 132269, 132270, 132271, 132272, 132273,
       132274, 132275, 132280, 132281, 132283, 132284, 132289, 132292,
       132293, 132294, 132295, 132296, 132297, 132298, 132299, 132300,
       132301, 132302, 132306, 132310, 132312, 132315, 132316, 132317,
       132318, 132319, 132321, 132324, 132326, 132328, 132329, 132330,
       132331, 132332, 132333, 132335, 132336, 132337, 132339, 132341,
       132342, 132343, 132344, 132345, 132346, 132347, 132348, 132349,
       132350, 132351, 132352, 132353, 132354, 132355, 132356, 132357,
       132358, 132359, 132360, 132361, 132362, 132363, 132364, 132365,
       132366, 132367, 132372, 132377, 132380, 132381, 132384, 132386,
       132387, 132389, 132392, 132393, 132395, 132396, 132398, 132399,
       132402, 132406, 132407, 132408, 132409, 132410, 132413, 132414,
       132417, 132419, 132421, 132425, 132429, 132430, 132432, 132433,
       132434, 132435, 132436, 132437, 132438, 132439, 132440, 132441,
       132442, 132443, 132444, 132445, 132446, 132447, 132448, 132449,
       132450, 132451, 132452, 132453, 132454, 132455, 132456, 132457,
       132458, 132459, 132464, 132468, 132469, 132470, 132474, 132477,
       132478, 132479, 132481, 132482, 132483, 132484, 132485, 132487,
       132488, 132491, 132493, 132498, 132509, 132511, 132513, 132514,
       132517, 132518, 132519, 132521, 132522, 132523, 132524, 132525,
       132526, 132527, 132528, 132529, 132530, 132531, 132532, 132533,
       132535, 132536, 132537, 132538, 132539, 132540, 132541, 132542,
       132543, 132544, 132545, 132546, 132547, 132548, 132549, 132550,
       132551, 132555, 132557, 132560, 132561, 132562, 132563, 132564,
       132565, 132566, 132567, 132568, 132569, 132570, 132571, 132572,
       132573, 132574, 132575, 132576, 132577, 132578, 132579, 132580,
       132581, 132582, 132583, 132584, 132585, 132586, 132587, 132588,
       132589, 132590, 132591, 132592, 132593, 132594, 132595, 132596,
       132597, 132598, 132599, 132600, 132601, 132602, 132603, 132604,
       132605, 132606, 132607, 132608, 132609, 132610, 132611, 132612,
       132613, 132614, 132615, 132616, 132617, 132618, 132619, 132620,
       132621, 132622, 132623, 132624, 132625, 132626, 132628, 132629,
       132630, 132631, 132632, 132633, 132634, 132635, 132636, 132637,
       132638, 132639, 132640, 132641, 132642, 132643, 132644, 132645,
       132646, 132647, 132648, 132649, 132650, 132651, 132652, 132653,
       132654, 132655, 132656, 132657, 132658, 132659, 132660, 132661,
       132662, 132663, 132664, 132665, 132666, 132667, 132668, 132669,
       132670, 132671, 132672, 132673, 132674, 132675, 132676, 132677,
       132678, 132679, 132680, 132681, 132682, 132683, 132684, 132685,
       132686, 132687, 132688, 132689, 132690, 132691, 132692, 132693,
       132694, 132695, 132696, 132697, 132698, 132699, 132700, 132701,
       132702, 132703, 132704, 132705, 132706, 132707, 132708, 132709,
       132710, 132711, 132712, 132713, 132714, 132715, 132716, 132717,
       132718, 132719, 132720, 132721, 132722, 132723, 132724, 132725,
       132726, 132727, 132728, 132729, 132730, 132731, 132732, 132733,
       132734, 132735, 132736, 132737, 132738, 132739, 132740, 132741,
       132742, 132743, 132744, 132745, 132746, 132747, 132748, 132749,
       132750, 132751, 132752, 132753, 132754, 132755, 132756, 132757,
       132758, 132759, 132760, 132761, 132762, 132763, 132764, 132765,
       132766, 132767, 132768, 132769, 132770, 132771, 132772, 132773,
       132774, 132775, 132776, 132777, 132778, 132779, 132780, 132781,
       132782, 132783, 132784, 132785, 132786, 132787, 132788, 132789,
       132790, 132791, 132792, 132793, 132794, 132795, 132796, 132797,
       132798, 132799, 132801, 132802, 132803, 132804, 132805, 132806,
       132807, 132808, 132809, 132810, 132811, 132812, 132813, 132815,
       132816, 132817, 132818, 132819, 132820, 132821, 132822, 132823,
       132824, 132825, 132826, 132827, 132828, 132829, 132830, 132831,
       132832, 132833, 132834, 132835, 132836, 132837, 132838, 132839,
       132840, 132841, 132842, 132843, 132844, 132845, 132846, 132847,
       132848, 132849, 132850, 132851, 132852, 132853, 132854, 132855,
       132856, 132857, 132858, 132859, 132860, 132861, 132862, 132863,
       132864, 132865, 132866, 132867, 132868, 132869, 132870, 132871,
       132872, 132873, 132874, 132875, 132876, 132877, 132878, 132879,
       132880, 132881, 132882, 132883, 132884, 132885, 132886, 132887,
       132888, 132889, 132890, 132891, 132892, 132893, 132894, 132895,
       132896, 132897, 132898, 132899, 132900, 132901, 132902, 132903,
       132904, 132905, 132906, 132907, 132908, 132909, 132910, 132911,
       132912, 132913, 132914, 132915, 132916, 132917, 132918, 132919,
       132920, 132921, 132922, 132923, 132924, 132925, 132926, 132927,
       132928, 132929, 132930, 132931, 132932, 132933, 132934, 132935,
       132936, 132937, 132938, 132939, 132940, 132941, 132942, 132943,
       132944, 132945, 132946, 132947, 132948, 132950, 132951, 132953,
       132954, 132955, 132956, 132957, 132958, 132959, 132960, 132961,
       132962, 132963, 132964, 132965, 132966, 132967, 132968, 132969,
       132970, 132971, 132972, 132973, 132974, 132975, 132976, 132977,
       132978, 132979, 132980, 132981, 132982, 132983, 132984, 132985,
       132986, 132992, 132993, 132994, 132995, 132996, 132997, 132998,
       132999, 133000, 133001, 133002, 133003, 133004, 133005, 133006,
       133007, 133008, 133009, 133010, 133011, 133012, 133013, 133014,
       133015, 133016, 133017, 133018, 133019, 133020, 133021, 133022,
       133023, 133024, 133025, 133026, 133027, 133028, 133029, 133030,
       133031, 133032, 133033, 133034, 133035, 133036, 133037, 133038,
       133039, 133040, 133041, 133042, 133043, 133047, 133048, 133049,
       134970, 134971, 134972, 134973, 134974, 134975, 134976, 134977,
       134978, 134979, 134980, 134981, 134982, 134983, 134984, 134985,
       134986, 134987, 134988, 134989, 134990, 134991, 134992, 134993,
       134994, 134995, 134996, 134997, 134998, 134999, 135000, 135001,
       135002, 135003, 135004, 135005, 135006, 135007, 135008, 135009,
       135010, 135011, 135012, 135013, 135014, 135015, 135016, 135017,
       135018, 135019, 135020, 135021, 135022, 135023, 135024, 135025,
       135026, 135027, 135028, 135029, 135030, 135031, 135032, 135033,
       135034, 135035, 135036, 135037, 135038, 135039, 135040, 135041,
       135042, 135043, 135044, 135045, 135046, 135047, 135048, 135049,
       135050, 135051, 135052, 135053, 135054, 135055, 135056, 135057,
       135058, 135059, 135060, 135061, 135062, 135063, 135064, 135065,
       135066, 135067, 135068, 135069, 135070, 135071, 135072, 135073,
       135074, 135075, 135076, 135077, 135078, 135079, 135080, 135081,
       135082, 135084, 135085, 135086, 135088, 135089, 135090, 135091,
       135092, 135093, 135094, 135097, 135098, 135099, 135100, 135101,
       135102, 135103, 135104, 135105, 135106, 135107, 135108, 135109,
       135110, 135111])

In [15]:
# Menggabungkan seluruh userID
user_all = np.concatenate((
    usercuisine.userID.unique(),
    payment.userID.unique(),
    profile.userID.unique()
))
 
# Menghapus data yang sama kemudian mengurutkannya
user_all = np.sort(np.unique(user_all)) 
 
print('Jumlah seluruh user: ', len(user_all))

Jumlah seluruh user:  138

In [16]:
# Menggabungkan file accepts, geo, parking, hours ke dalam dataframe resto_info 
resto_info = pd.concat([accepts, geo, parking, hours])
 
# Menggabungkan dataframe rating dengan resto_info berdasarkan nilai placeID
resto = pd.merge(rating, resto_info , on='placeID', how='left')
resto_info

      placeID             Rpayment  ...         hours                  days
0      135110                 cash  ...           NaN                   NaN
1      135110                 VISA  ...           NaN                   NaN
2      135110  MasterCard-Eurocard  ...           NaN                   NaN
3      135110     American_Express  ...           NaN                   NaN
4      135110     bank_debit_cards  ...           NaN                   NaN
...       ...                  ...  ...           ...                   ...
2334   132012                  NaN  ...  12:00-22:00;                  Sun;
2335   132012                  NaN  ...  12:00-22:00;  Mon;Tue;Wed;Thu;Fri;
2336   132012                  NaN  ...  12:00-22:00;  Mon;Tue;Wed;Thu;Fri;
2337   132012                  NaN  ...  12:00-22:00;                  Sat;
2338   132012                  NaN  ...  12:00-22:00;                  Sat;

[4485 rows x 25 columns]

In [17]:
# Cek missing value dengan fungsi isnull()
resto.isnull().sum()

userID               0
placeID              0
rating               0
food_rating          0
service_rating       0
Rpayment          5781
latitude          6917
longitude         6917
the_geom_meter    6917
name              6917
address           6917
city              6917
state             6917
country           6917
fax               6917
zip               6917
alcohol           6917
smoking_area      6917
dress_code        6917
accessibility     6917
price             6917
url               6917
Rambience         6917
franchise         6917
area              6917
other_services    6917
parking_lot       6917
hours             4619
days              4619
dtype: int64

In [18]:
# Menghitung jumlah rating, food_rating, dan service kemudian menggabungkannya berdasarkan placeID
resto.groupby('placeID').sum()

         rating  food_rating  service_rating    latitude    longitude
placeID
132560       12           24               6   95.009216  -396.667653
132561       15           20              20   94.907276  -396.506024
132564       25           25              30   94.923698  -396.580739
132572       90           90              84  332.124707 -1514.890677
132583       24           24              30   75.689162  -396.937328
...         ...          ...             ...         ...          ...
135088       36           42              36  113.256068  -595.319338
135104       48           80              48  166.270875  -694.179039
135106       96           96              96  221.497088 -1009.760928
135108       65           65              55  243.498787 -1110.269437
135109       24           30              18   75.687139  -396.941400

[130 rows x 5 columns]

In [19]:
# Definisikan dataframe rating ke dalam variabel all_resto_rate
all_resto_rate = rating
all_resto_rate

     userID  placeID  rating  food_rating  service_rating
0     U1077   135085       2            2               2
1     U1077   135038       2            2               1
2     U1077   132825       2            2               2
3     U1077   135060       1            2               2
4     U1068   135104       1            1               2
...     ...      ...     ...          ...             ...
1156  U1043   132630       1            1               1
1157  U1011   132715       1            1               0
1158  U1068   132733       1            1               0
1159  U1068   132594       1            1               1
1160  U1068   132660       0            0               0

[1161 rows x 5 columns]

In [20]:
# Menggabungkan all resto_rate dengan dataframe geo berdasarkan placeID
all_resto_name = pd.merge(all_resto_rate, geo[['placeID','name']], on='placeID', how='left')
 
# Print dataframe all_resto_name
all_resto_name

     userID  placeID  ...  service_rating                                   name
0     U1077   135085  ...               2                 Tortas Locas Hipocampo
1     U1077   135038  ...               1                  Restaurant la Chalita
2     U1077   132825  ...               2                        puesto de tacos
3     U1077   135060  ...               2                Restaurante Marisco Sam
4     U1068   135104  ...               2                                   vips
...     ...      ...  ...             ...                                    ...
1156  U1043   132630  ...               1                             palomo tec
1157  U1011   132715  ...               0                   tacos de la estacion
1158  U1068   132733  ...               0                          Little Cesarz
1159  U1068   132594  ...               1     tacos de barbacoa enfrente del Tec
1160  U1068   132660  ...               0  carnitas mata calle Emilio Portes Gil

[1161 rows x 6 columns]

In [21]:
# Menggabungkan dataframe cuisine dengan all_resto_name dan memasukkannya ke dalam variabel all_resto 
all_resto = pd.merge(all_resto_name, cuisine, on='placeID', how='left')
all_resto

     userID  placeID  ...                                   name   Rcuisine
0     U1077   135085  ...                 Tortas Locas Hipocampo  Fast_Food
1     U1077   135038  ...                  Restaurant la Chalita        NaN
2     U1077   132825  ...                        puesto de tacos    Mexican
3     U1077   135060  ...                Restaurante Marisco Sam    Seafood
4     U1068   135104  ...                                   vips    Mexican
...     ...      ...  ...                                    ...        ...
1326  U1043   132630  ...                             palomo tec    Mexican
1327  U1011   132715  ...                   tacos de la estacion    Mexican
1328  U1068   132733  ...                          Little Cesarz   Pizzeria
1329  U1068   132594  ...     tacos de barbacoa enfrente del Tec    Mexican
1330  U1068   132660  ...  carnitas mata calle Emilio Portes Gil        NaN

[1331 rows x 7 columns]

In [22]:
# Membersihkan missing value dengan fungsi dropna()
all_resto_clean = all_resto.dropna()
all_resto_clean

     userID  placeID  ...                                name   Rcuisine
0     U1077   135085  ...              Tortas Locas Hipocampo  Fast_Food
2     U1077   132825  ...                     puesto de tacos    Mexican
3     U1077   135060  ...             Restaurante Marisco Sam    Seafood
4     U1068   135104  ...                                vips    Mexican
5     U1068   132740  ...       Carreton de Flautas y Migadas    Mexican
...     ...      ...  ...                                 ...        ...
1325  U1043   132732  ...                  Taqueria EL amigo     Mexican
1326  U1043   132630  ...                          palomo tec    Mexican
1327  U1011   132715  ...                tacos de la estacion    Mexican
1328  U1068   132733  ...                       Little Cesarz   Pizzeria
1329  U1068   132594  ...  tacos de barbacoa enfrente del Tec    Mexican

[1043 rows x 7 columns]

In [23]:
# Mengecek kembali missing value pada variabel all_resto_clean
all_resto_clean.isnull().sum()

userID            0
placeID           0
rating            0
food_rating       0
service_rating    0
name              0
Rcuisine          0
dtype: int64

In [24]:
# Mengurutkan resto berdasarkan PlaceID kemudian memasukkannya ke dalam variabel fix_resto
fix_resto = all_resto_clean.sort_values('placeID', ascending=True)
fix_resto

     userID  placeID  ...                        name   Rcuisine
1303  U1087   132560  ...          puesto de gorditas   Regional
1288  U1050   132560  ...          puesto de gorditas   Regional
14    U1067   132560  ...          puesto de gorditas   Regional
42    U1082   132560  ...          puesto de gorditas   Regional
1052  U1013   132572  ...                Cafe Chaires  Cafeteria
...     ...      ...  ...                         ...        ...
438   U1024   135106  ...  El Rincón de San Francisco    Mexican
178   U1020   135109  ...                   Paniroles    Italian
1071  U1041   135109  ...                   Paniroles    Italian
99    U1030   135109  ...                   Paniroles    Italian
180   U1051   135109  ...                   Paniroles    Italian

[1043 rows x 7 columns]

In [25]:
# Mengecek berapa jumlah fix_resto
len(fix_resto.placeID.unique())

95

In [26]:
# Mengecek kategori masakan yang unik
fix_resto.Rcuisine.unique()

array(['Regional', 'Cafeteria', 'American', 'Mexican', 'Fast_Food',
       'Italian', 'Armenian', 'Pizzeria', 'Japanese', 'Vietnamese',
       'Family', 'International', 'Game', 'Burgers', 'Bakery', 'Bar',
       'Breakfast-Brunch', 'Bar_Pub_Brewery', 'Mediterranean',
       'Cafe-Coffee_Shop', 'Contemporary', 'Seafood', 'Chinese'],
      dtype=object)

In [27]:
# Mengecek kategori masakan Game 
fix_resto[fix_resto['Rcuisine'] == 'Game']

     userID  placeID  rating  food_rating  service_rating name Rcuisine
781   U1015   132851       1            1               1  KFC     Game
509   U1052   132851       1            0               2  KFC     Game
708   U1008   132851       1            1               1  KFC     Game
770   U1037   132851       2            2               1  KFC     Game
574   U1069   132851       1            0               0  KFC     Game
1188  U1131   132851       2            2               2  KFC     Game
764   U1111   132851       2            1               0  KFC     Game

In [28]:
# Mengecek kategori masakan pada nama restoran KFC
fix_resto[fix_resto['name'] == 'KFC']

     userID  placeID  rating  food_rating  service_rating name  Rcuisine
781   U1015   132851       1            1               1  KFC      Game
508   U1052   132851       1            0               2  KFC  American
780   U1015   132851       1            1               1  KFC  American
509   U1052   132851       1            0               2  KFC      Game
708   U1008   132851       1            1               1  KFC      Game
707   U1008   132851       1            1               1  KFC  American
770   U1037   132851       2            2               1  KFC      Game
769   U1037   132851       2            2               1  KFC  American
1187  U1131   132851       2            2               2  KFC  American
574   U1069   132851       1            0               0  KFC      Game
1188  U1131   132851       2            2               2  KFC      Game
764   U1111   132851       2            1               0  KFC      Game
763   U1111   132851       2            1               0  KFC  American
573   U1069   132851       1            0               0  KFC  American

In [29]:
# Mengubah nama kategori masakan ‘Game’ menjadi ‘American’
fix_resto = fix_resto.replace('Game', 'American')
fix_resto[fix_resto['name'] == 'KFC']

     userID  placeID  rating  food_rating  service_rating name  Rcuisine
781   U1015   132851       1            1               1  KFC  American
508   U1052   132851       1            0               2  KFC  American
780   U1015   132851       1            1               1  KFC  American
509   U1052   132851       1            0               2  KFC  American
708   U1008   132851       1            1               1  KFC  American
707   U1008   132851       1            1               1  KFC  American
770   U1037   132851       2            2               1  KFC  American
769   U1037   132851       2            2               1  KFC  American
1187  U1131   132851       2            2               2  KFC  American
574   U1069   132851       1            0               0  KFC  American
1188  U1131   132851       2            2               2  KFC  American
764   U1111   132851       2            1               0  KFC  American
763   U1111   132851       2            1               0  KFC  American
573   U1069   132851       1            0               0  KFC  American

In [30]:
# Membuat variabel preparation yang berisi dataframe fix_resto kemudian mengurutkan berdasarkan placeID
preparation = fix_resto
preparation.sort_values('placeID')

     userID  placeID  ...                        name   Rcuisine
1303  U1087   132560  ...          puesto de gorditas   Regional
1288  U1050   132560  ...          puesto de gorditas   Regional
14    U1067   132560  ...          puesto de gorditas   Regional
42    U1082   132560  ...          puesto de gorditas   Regional
184   U1055   132572  ...                Cafe Chaires  Cafeteria
...     ...      ...  ...                         ...        ...
1224  U1002   135106  ...  El Rincón de San Francisco    Mexican
99    U1030   135109  ...                   Paniroles    Italian
178   U1020   135109  ...                   Paniroles    Italian
1071  U1041   135109  ...                   Paniroles    Italian
180   U1051   135109  ...                   Paniroles    Italian

[1043 rows x 7 columns]

In [31]:
# Membuang data duplikat pada variabel preparation
preparation = preparation.drop_duplicates('placeID')
preparation

     userID  placeID  ...                                name   Rcuisine
1303  U1087   132560  ...                  puesto de gorditas   Regional
1052  U1013   132572  ...                        Cafe Chaires  Cafeteria
168   U1118   132583  ...                    McDonalds Centro   American
24    U1107   132584  ...                  Gorditas Dona Tota    Mexican
1329  U1068   132594  ...  tacos de barbacoa enfrente del Tec    Mexican
...     ...      ...  ...                                 ...        ...
681   U1095   135086  ...         Mcdonalds Parque Tangamanga  Fast_Food
175   U1020   135088  ...                   Cafeteria cenidet  Cafeteria
4     U1068   135104  ...                                vips    Mexican
488   U1004   135106  ...          El Rincón de San Francisco    Mexican
178   U1020   135109  ...                           Paniroles    Italian

[95 rows x 7 columns]

In [32]:
# Mengonversi data series ‘placeID’ menjadi dalam bentuk list
resto_id = preparation['placeID'].tolist()
 
# Mengonversi data series ‘Name’ menjadi dalam bentuk list
resto_name = preparation['name'].tolist()
 
# Mengonversi data series ‘Rcuisine’ menjadi dalam bentuk list
resto_cuisine = preparation['Rcuisine'].tolist()
 
print(len(resto_id))
print(len(resto_name))
print(len(resto_cuisine))

95
95
95

In [33]:
# Membuat dictionary untuk data ‘resto_id’, ‘resto_name’, dan ‘cuisine’
resto_new = pd.DataFrame({
    'id': resto_id,
    'resto_name': resto_name,
    'cuisine': resto_cuisine
})
resto_new

        id                          resto_name    cuisine
0   132560                  puesto de gorditas   Regional
1   132572                        Cafe Chaires  Cafeteria
2   132583                    McDonalds Centro   American
3   132584                  Gorditas Dona Tota    Mexican
4   132594  tacos de barbacoa enfrente del Tec    Mexican
..     ...                                 ...        ...
90  135086         Mcdonalds Parque Tangamanga  Fast_Food
91  135088                   Cafeteria cenidet  Cafeteria
92  135104                                vips    Mexican
93  135106          El Rincón de San Francisco    Mexican
94  135109                           Paniroles    Italian

[95 rows x 3 columns]

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
 
# Inisialisasi TfidfVectorizer
tf = TfidfVectorizer()
 
# Melakukan perhitungan idf pada data cuisine
tf.fit(resto_new['cuisine']) 
 
# Mapping array dari fitur index integer ke fitur nama
tf.get_feature_names()

['american',
 'armenian',
 'bar',
 'bar_pub_brewery',
 'breakfast',
 'brunch',
 'burgers',
 'cafe',
 'cafeteria',
 'chinese',
 'coffee_shop',
 'contemporary',
 'family',
 'fast_food',
 'international',
 'italian',
 'japanese',
 'mexican',
 'pizzeria',
 'regional',
 'seafood',
 'vietnamese']

In [36]:
# Melakukan fit lalu ditransformasikan ke bentuk matrix
tfidf_matrix = tf.fit_transform(resto_new['cuisine']) 
 
# Melihat ukuran matrix tfidf
tfidf_matrix.shape

(95, 22)

In [41]:
# Mengubah vektor tf-idf dalam bentuk matriks dengan fungsi todense()
tfidf_matrix.todense()

matrix([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [43]:
# Membuat dataframe untuk melihat tf-idf matrix
# Kolom diisi dengan jenis masakan
# Baris diisi dengan nama resto
 
pd.DataFrame(
    tfidf_matrix.todense(), 
    columns=tf.get_feature_names(),
    index=resto_new.resto_name
).sample(22, axis=1).sample(10, axis=0)

                                      coffee_shop  pizzeria  ...  italian  brunch
resto_name                                                   ...
Dominos Pizza                                 0.0       1.0  ...      0.0     0.0
KFC                                           0.0       0.0  ...      0.0     0.0
Gorditas Dona Tota                            0.0       0.0  ...      0.0     0.0
Cenaduria El RincÃ³n de Tlaquepaque           0.0       0.0  ...      0.0     0.0
Restaurant Wu Zhuo Yi                         0.0       0.0  ...      0.0     0.0
Restaurant Bar Coty y Pablo                   0.0       0.0  ...      0.0     0.0
McDonalds Centro                              0.0       0.0  ...      0.0     0.0
tacos de barbacoa enfrente del Tec            0.0       0.0  ...      0.0     0.0
Hamburguesas La perica                        0.0       0.0  ...      0.0     0.0
Restaurant Bar Hacienda los Martinez          0.0       0.0  ...      0.0     0.0

[10 rows x 22 columns]

In [44]:
from sklearn.metrics.pairwise import cosine_similarity
 
# Menghitung cosine similarity pada matrix tf-idf
cosine_sim = cosine_similarity(tfidf_matrix) 
cosine_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [46]:
# Membuat dataframe dari variabel cosine_sim dengan baris dan kolom berupa nama resto
cosine_sim_df = pd.DataFrame(cosine_sim, index=resto_new['resto_name'], columns=resto_new['resto_name'])
print('Shape:', cosine_sim_df.shape)
 
# Melihat similarity matrix pada setiap resto
cosine_sim_df.sample(5, axis=1).sample(10, axis=0)

Shape: (95, 95)

resto_name                           la perica hamburguesa  ...  tortas hawai
resto_name                                                  ...
Restaurante de Mariscos la Langosta                    0.0  ...           0.0
Hamburguesas La perica                                 0.0  ...           0.0
Restaurant Wu Zhuo Yi                                  0.0  ...           0.0
TACOS CORRECAMINOS                                     0.0  ...           0.0
Koye Sushi                                             0.0  ...           0.0
El cotorreo                                            0.0  ...           0.0
Restaurante Bar Fu-hao                                 0.0  ...           0.0
la Cantina                                             0.0  ...           0.0
puesto de tacos                                        0.0  ...           0.0
Restaurante Tiberius                                   0.0  ...           0.0

[10 rows x 5 columns]

In [48]:
def resto_recommendations(nama_resto, similarity_data=cosine_sim_df, items=resto_new[['resto_name', 'cuisine']], k=5):
    """
    Rekomendasi Resto berdasarkan kemiripan dataframe
 
    Parameter:
    ---
    nama_resto : tipe data string (str)
                Nama Restoran (index kemiripan dataframe)
    similarity_data : tipe data pd.DataFrame (object)
                      Kesamaan dataframe, simetrik, dengan resto sebagai 
                      indeks dan kolom
    items : tipe data pd.DataFrame (object)
            Mengandung kedua nama dan fitur lainnya yang digunakan untuk mendefinisikan kemiripan
    k : tipe data integer (int)
        Banyaknya jumlah rekomendasi yang diberikan
    ---
 
 
    Pada index ini, kita mengambil k dengan nilai similarity terbesar 
    pada index matrix yang diberikan (i).
    """
 
 
    # Mengambil data dengan menggunakan argpartition untuk melakukan partisi secara tidak langsung sepanjang sumbu yang diberikan    
    # Dataframe diubah menjadi numpy
    # Range(start, stop, step)
    index = similarity_data.loc[:,nama_resto].to_numpy().argpartition(
        range(-1, -k, -1))
    
    # Mengambil data dengan similarity terbesar dari index yang ada
    closest = similarity_data.columns[index[-1:-(k+2):-1]]
    
    # Drop nama_resto agar nama resto yang dicari tidak muncul dalam daftar rekomendasi
    closest = closest.drop(nama_resto, errors='ignore')
 
    return pd.DataFrame(closest).merge(items).head(k)

In [51]:
resto_new[resto_new.resto_name.eq('KFC')]

        id resto_name   cuisine
31  132851        KFC  American

In [54]:
resto_recommendations('KFC')

           resto_name        cuisine
0                VIPS       American
1  tacos los volcanes       American
2     Pizzeria Julios       American
3             Sirlone  International
4    McDonalds Centro       American